import { motion } from "framer-motion";
import Footer from "../components/Footer";

export default function Cookie() {
  return (
    <main
      style={{
        background: "#0e0e0e",
        color: "#fff",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
      }}
    >
      <div
        style={{
          flexGrow: 1,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          padding: "10vh 4vw 6vh",
        }}
      >
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          style={{
            maxWidth: "820px",
            width: "100%",
            textAlign: "center",
            lineHeight: 1.7,
          }}
        >
          <h1
            style={{
              fontSize: "clamp(32px, 6vw, 56px)",
              letterSpacing: "0.06em",
              marginBottom: "1.2rem",
            }}
          >
            Cookie Policy 
          </h1>

          <p style={{ opacity: 0.85 }}>
            This website does not actively use cookies or tracking technologies.
          </p>

          <div style={{ textAlign: "left", marginTop: "2.5rem" }}>
            <h3 style={{ opacity: 0.9 }}>1. No cookie collection</h3>
            <p style={{ opacity: 0.8 }}>
              I do not collect, analyze, or store cookies on this site.  
              Any cookies that may appear are automatically generated by your browser or hosting provider and are not used by me for tracking or analytics.
            </p>

            <h3 style={{ marginTop: "2rem", opacity: 0.9 }}>2. Third-party content</h3>
            <p style={{ opacity: 0.8 }}>
              Embedded or external content (like linked media or GitHub embeds) may set their own cookies.  
              Please refer to their individual privacy policies if you interact with them.
            </p>

            <h3 style={{ marginTop: "2rem", opacity: 0.9 }}>3. Updates</h3>
            <p style={{ opacity: 0.8 }}>
              If cookie usage ever changes, this page will be updated accordingly.
            </p>
          </div>
        </motion.div>
      </div>

      <Footer />
    </main>
  );
}
